# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # build the container
      - run: make build

      # login to Docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # push the container
      - run: make push

      # deploy to DEV
      # install python and awscli
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev jq
            sudo pip install awscli

      # Issue Command
      - run: make deploy
